apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pre-scaling-operator-edit-cluster-role
  namespace: devops-scaling-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - patch
  - update
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - patch
  - update
- apiGroups:
  - redis.containersolutions.com
  resources:
  - redisclusters
  verbs:
  - patch
  - update
