# permissions for end users to view clusterscalingstatedefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterscalingstatedefinition-viewer-role
rules:
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstatedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstatedefinitions/status
  verbs:
  - get
