# permissions for end users to view clusterscalingstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterscalingstate-viewer-role
rules:
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstates/status
  verbs:
  - get
