# permissions for end users to view scalingstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scalingstate-viewer-role
rules:
- apiGroups:
  - scaling.prescale.com
  resources:
  - scalingstates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.prescale.com
  resources:
  - scalingstates/status
  verbs:
  - get
