apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pre-scaling-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pre-scaling-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: pre-scaling-operator-sa
  namespace: system
