apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: pre-scaling-operator
  name: pre-scaling-operator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: pre-scaling-operator
status:
  loadBalancer: {}
