apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "scaling.prescale.com/v1alpha1",
          "config": {
            "dryRun": false
          },
          "kind": "ClusterScalingState",
          "metadata": {
            "name": "clusterscalingstate-sample-test"
          },
          "spec": {
            "scalingClass": "test",
            "state": "bau"
          }
        },
        {
          "apiVersion": "scaling.prescale.com/v1alpha1",
          "config": {
            "dryRun": false
          },
          "kind": "ClusterScalingStateDefinition",
          "metadata": {
            "name": "global-state-definition"
          },
          "spec": [
            {
              "description": "Maximum scaling settings",
              "name": "peak",
              "priority": 1
            },
            {
              "description": "Higher expected load after a marketing run. Possibly an email blast or twitter share.",
              "name": "marketing-run",
              "priority": 5
            },
            {
              "description": "Business as usual",
              "name": "bau",
              "priority": 10
            }
          ]
        },
        {
          "apiVersion": "scaling.prescale.com/v1alpha1",
          "config": {
            "dryRun": false
          },
          "kind": "ScalingState",
          "metadata": {
            "name": "scalingstate-product"
          },
          "spec": {
            "state": "peak"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.10.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: pre-scaling-operator.v0.3.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterScalingStateDefinition is the Schema for the clusterscalingstatedefinitions
        API
      displayName: Cluster Scaling State Definition
      kind: ClusterScalingStateDefinition
      name: clusterscalingstatedefinitions.scaling.prescale.com
      version: v1alpha1
    - description: ClusterScalingState is the Schema for the clusterscalingstates
        API
      displayName: Cluster Scaling State
      kind: ClusterScalingState
      name: clusterscalingstates.scaling.prescale.com
      version: v1alpha1
    - description: ScalingState is the Schema for the scalingstates API
      displayName: Scaling State
      kind: ScalingState
      name: scalingstates.scaling.prescale.com
      version: v1alpha1
  description: An operator for significant scaling needs
  displayName: containersol/pre-scaling-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - resourcequotas
          verbs:
          - list
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - redis.containersolutions.com
          resources:
          - redisclusters
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - scaling.prescale.com
          resources:
          - clusterscalingstatedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - scaling.prescale.com
          resources:
          - clusterscalingstatedefinitions/finalizers
          verbs:
          - update
        - apiGroups:
          - scaling.prescale.com
          resources:
          - clusterscalingstatedefinitions/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - scaling.prescale.com
          resources:
          - clusterscalingstates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - scaling.prescale.com
          resources:
          - clusterscalingstates/finalizers
          verbs:
          - update
        - apiGroups:
          - scaling.prescale.com
          resources:
          - clusterscalingstates/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - scaling.prescale.com
          resources:
          - scalingstates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - scaling.prescale.com
          resources:
          - scalingstates/finalizers
          verbs:
          - update
        - apiGroups:
          - scaling.prescale.com
          resources:
          - scalingstates/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: pre-scaling-operator-sa
      deployments:
      - name: pre-scaling-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: pre-scaling-operator
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: pre-scaling-operator
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /manager
                env:
                - name: MaxConcurrentNamespaceReconciles
                  value: "5"
                image: docker.io/pathogen/scaler-operator:0.3.2
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: "1"
                    memory: 800Mi
                securityContext:
                  allowPrivilegeEscalation: false
              serviceAccountName: pre-scaling-operator-sa
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - patch
          - update
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - patch
          - update
        - apiGroups:
          - redis.containersolutions.com
          resources:
          - redisclusters
          verbs:
          - patch
          - update
        - apiGroups:
          - ""
          - coordination.k8s.io
          resources:
          - configmaps
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: pre-scaling-operator-sa
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kubernetes
  - prescaling
  links:
  - name: Pre Scaling Operator
    url: https://pre-scaling-operator.domain
  maintainers:
  - email: andreas131313@gmail.com
    name: Andreas Krivas
  maturity: alpha
  provider:
    name: Container Solutions
  version: 0.3.2
