resources:
- operator.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - pre_scaling_operator_config.yaml
  name: pre-scaling-operator-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: containersol/pre-scaling-operator
  newName: docker.io/containersol/pre-scaling-operator
  newTag: 0.2.9
- name: controller
  newName: containersol/pre-scaling-operator
  newTag: ci
