apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: pre-scaling-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre-scaling-operator
  namespace: system
  labels:
<<<<<<< HEAD:config/manager/manager.yaml
    control-plane: pre-scaling-operator
    operator-name: pre-scaling-operator
=======
    
>>>>>>> main:config/apps/operator.yaml
spec:
  selector:
    matchLabels:
      control-plane: pre-scaling-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: pre-scaling-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: containersol/pre-scaling-operator:ci
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
           limits:
             cpu: "1"
             memory: 800Mi
        env:
          - name: MaxConcurrentNamespaceReconciles
            value: "5"
      serviceAccountName: pre-scaling-operator-sa
      terminationGracePeriodSeconds: 10
