name: PreScaleOperator
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - edited
      - created

env:
  CR_USER: ${{ secrets.CR_USER }}
  CR_PAT: ${{ secrets.CR_PAT }}
  DH_USER: ${{ secrets.DOCKERHUB_USER }}
  DH_TOKEN: ${{ secrets.DOCKERHUB_PASS }}
  OKD_GITHUB_TOKEN: ${{ secrets.OKD_GITHUB_TOKEN }}
  CR_GCP: ${{ secrets.CR_GCP }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_LOCATION: ${{ secrets.GKE_LOCATION }}
  

jobs:
  tests-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Go Modules
        run: |
          go mod download
      - name: Setup Operator SDK
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.4.2/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64 && sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
      - name: Setup KubeBuilder
        run: |
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin


      - id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_LOCATION }}
          credentials: ${{ secrets.CR_GCP }}

      - name: Configuring and testing k8s
        run: |
          kubectl get nodes
          kubectl create ns e2e-tests
 
      - name: Run tests for Kubernetes
        run: |
          make test

      - name: OKD Cluster login
        run: |
          oc login https://api.prescaling-operator-dev.openshift.csol.cloud:6443 --token='${{ env.OKD_GITHUB_TOKEN }}' --insecure-skip-tls-verify

      - name: Run tests for Openshift
        run: |
          make test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker ghcr.io login
        run: echo '${{ env.CR_PAT }}' | docker login ghcr.io -u ${{ env.CR_USER }} --password-stdin

      - name: Docker login
        run: echo '${{ env.DH_TOKEN }}' | docker login -u ${{ env.DH_USER }} --password-stdin

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/containersolutions/pre-scaling-operator,containersol/pre-scaling-operator
          tag-sha: true
          tag-custom: ci
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
