apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator-1
  annotations:
    scaler/type: "scale-once" # Change to 'autoscale' to allow scaling up
    scaler/state-peak-replicas: "5"
    scaler/state-bau-replicas: "3"
    scaler/state-default-replicas: "1"
  labels:
    app: random-generator-1
    scaler/opt-in: "true"
spec:
  selector:
    matchLabels:
      app: random-generator-1
  template:
    metadata:
      labels:
        app: random-generator-1
    spec:
      containers:
        - name: random-generator
          imagePullPolicy: Always
          image: chriscmsoft/random-generator:latest
          resources:
            requests:
              cpu: "60m"
              memory: "80Mi"
            limits:
              cpu: "120m"
              memory: "100Mi"


              